# Generated by Django 4.2.5 on 2023-09-07 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('situacao', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.curso')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinasSemestre',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.disciplina')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.semestre')),
            ],
        ),
        migrations.CreateModel(
            name='AlunosPendentes',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.aluno')),
                ('disciplina_semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.disciplinassemestre')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.curso'),
        ),
    ]
