# Generated by Django 4.2.5 on 2023-09-10 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_alter_semestre_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.curso')),
            ],
        ),
    ]
