# Generated by Django 4.2.5 on 2023-09-10 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('disciplina_semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.disciplinassemestre')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.professor')),
            ],
        ),
    ]
