# Generated by Django 4.2.5 on 2023-09-11 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_alter_turma_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.professor'),
        ),
        migrations.CreateModel(
            name='AlunosMatriculados',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('auno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.turma')),
            ],
        ),
    ]
