# Generated by Django 4.2.5 on 2023-09-11 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_alter_turma_professor_alunosmatriculados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='disciplina_semestre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.disciplinassemestre'),
        ),
    ]
