# Generated by Django 4.2.5 on 2023-09-11 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_alter_turma_disciplina_semestre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alunosmatriculados',
            old_name='auno',
            new_name='aluno',
        ),
    ]
