# Generated by Django 4.2.5 on 2023-09-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_rename_auno_alunosmatriculados_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='numero_semestre',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
