# Generated by Django 4.2.5 on 2023-09-17 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_disciplina_numero_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='disciplina_semestre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.disciplinassemestre'),
        ),
    ]
